### ISSUE TITLE
Translate Freecodecamp project to Portuguese(Brazilian)

### ISSUE THREAD

**Issue by TheCSharpAcademy** [TheCSharpAcademy/TCSA.V2#18]
Checklist:
0 - Modify the title of the issue to Translate Freecodecamp to <your language here> 
1 - Verify the other translation issues for this project to make sure nobody else is translating the same language as you. There will be several tickets open for the same project without a specified language.
2 - Once you pick a language, you'll have to add a new enum to Enums.Language (in the helpers folder)
3 - In ProjectHelper and StandAloneProjectsHelper, add a method to get projects in your language
4 - Translate Title, all text and if possible find resources in that language to replace the ones we have
5 - Make sure your check, double check and if possible use a grammar review website, since I won't be able to check the correctness of most languages.
6 - In Project Page, add references to your language wherever needed
7 - Test the language dropdown and assure it changes the text to the desired language.
8 - Be ready for some back-and-forth. Everything has to be working IMMACULATELY.
9 - Ask questions and give feedback on how we could make a reviewer's life easier.
10 - Don't forget not to FORK the repository. Instead create a BRANCH, we'll only accept pull requests from a branch created from the "create a branch" link you can see on your right.
11 - Make sure you pull changes from DEVELOPMENT into your branch. Especially when you are about to create the PR. There might be merge conflicts.

**Comment by VocalNight** [comment]
https://github.com/TheCSharpAcademy/TCSA.V2/commit/48b8a1378aebc2451499a726a6a33c1a036ae09a

**Comment by VocalNight** [comment]
#42
