### ISSUE TITLE
Fix Project Approved Notification

### ISSUE THREAD

**Issue by TheCSharpAcademy** [TheCSharpAcademy/TCSA.V2#345]
At the moment notifications in the code reviews area are black and white. Use the recently created ResponseCard instead.

![Image](https://github.com/TheCSharpAcademy/TCSA.V2/assets/108711476/9dc99972-afd6-4840-9006-a3662e85aa55)

**Comment by kimfom01** [comment]
@TheCSharpAcademy I can't find the `ResponseCard`  that was mentioned in the issue description. Please could you point it out or it doesn't exist yet?

**Comment by kimfom01** [comment]
@TheCSharpAcademy  or do you mean `ResultCard`?

**Comment by kimfom01** [comment]
Is this what you want to be implemented? @TheCSharpAcademy ![image](https://github.com/user-attachments/assets/4558b1e3-e628-45a1-835f-e5dbd2f81056)
