### ISSUE TITLE
Add Count to Project Page

### ISSUE THREAD

**Issue by TheCSharpAcademy** [TheCSharpAcademy/TCSA.V2#387]
In the project page I'd like to display "This project was completed by {x} students" somewhere at the top (but after the banner).

**Comment by ukpagrace** [comment]
@TheCSharpAcademy  How is a completed project determined?

**Comment by TheCSharpAcademy** [comment]
@ukpagrace You should be able to figure out by studying the code. I'd like you to try before giving you the answer, since this is a big part of what you'll have to do in a professional environment 😄. Feel free to ask later if you still can't find it.

**Comment by ukpagrace** [comment]
okay :)

**Comment by ukpagrace** [comment]
I looked through the code and the Dashboard Poject and i can see Iscompeleted and IsPendingReview
IsCompleted is for when the user completes the reading and makes it as completed while is PendingReview is when they submit a pr for the project  and is approved 

And  IsPendingReview is the one I am using, but i have a question 
users that dont submit using with the code review link do they still go through this process?

**Comment by ukpagrace** [comment]
https://github.com/TheCSharpAcademy/TCSA.V2/pull/388
