### ISSUE TITLE
Allow users to edit PR URL after submission

### ISSUE THREAD

**Issue by stevietv** [TheCSharpAcademy/TCSA.V2#389]
Currently once a project is submitted the user can no longer edit their submission.
There should be a method for a user to edit a submission pending review.

**Comment by ukpagrace** [comment]
Hey,Can I work on this?

**Comment by stevietv** [comment]
yes, the issue was created for anyone to pick up!

**Comment by ukpagrace** [comment]
Okay

**Comment by ukpagrace** [comment]
closes #392
